### ISSUE TITLE
Denial of Service via a crafted email containing a few million multiparts

### ISSUE THREAD

**Issue by gabegorelick** [andris9/mailsplit#4]
From https://snyk.io/vuln/npm:mailsplit:20180625:

> Affected versions of this package are vulnerable to Denial of Service (DoS) attacks via a crafted email containing a few million multiparts.
>
> MIME (Multipurpose Internet Mail Extentions) is an internet standard that extends the format of email to support: Non-ACSII character sets, non-text attachments, and more.
> 
> Most Node.js MIME decoders do not validate the number of multiparts they are willing to decode, allowing an attacker to send a crafted email containing a few million multiparts, which will then block the Node.js event loop for tens of seconds, explode RAM usage, and cause an out of memory crash.

**Comment by andris9** [comment]
The report was moot and does not apply to mailsplit.

**Comment by gabegorelick** [comment]
@andris9 Thanks, I figured as much but couldn't find a public statement from you. Do you have any more info on why this does not apply to mailsplit?

**Comment by andris9** [comment]
As it turned out the benchmark script used against all these mail parsing libraries failed to test mailsplit properly. Mailsplit did not treat a mime node without a header as a node but a text line so what the test tested was not millions of child nodes but a single text node with millions of lines of text content. I did change mailsplit behavior so it would look better in that test but never cared to report the module as “fixed”

**Comment by gabegorelick** [comment]
Thanks again! I went ahead and contacted snyk and it sounds like they'll mark it as fixed in their DB. So hopefully you don't have to deal with this report again in the future :)
